#! /bin/sh

# Check parameters
declare USAGE="\nUsage: $0 <interference config> <l1 cache config> <l2 cache config> <number of cores>\n\nThis script invokes the Chronos analyzer for the given benchmark and configuration."

if (( $# != 4 )); then
  echo -e $USAGE;
  exit 1;
fi;

declare    INTERFERENCE_FILE=$1
declare    L1_CACHE_CONFIG=$2
declare    L2_CACHE_CONFIG=$3
declare -i NUMBER_OF_CORES=$4
declare    ANALYZER_DIR=m_cache

# Do the call
${ANALYZER_DIR}/opt $INTERFERENCE_FILE $L1_CACHE_CONFIG $L2_CACHE_CONFIG $NUMBER_OF_CORES
