#!/bin/sh

if
  /home/sudiptac/sudiptac/Work/bin/sslittle-na-sstrix-gcc -g -o $1 $1.c
then
  /home/sudiptac/sudiptac/Work/bin/sslittle-na-sstrix-objdump -dlS --disassemble-zeroes --prefix-addresses $1 >& $1.dis
  /home/sudiptac/sudiptac/Work/bin/sslittle-na-sstrix-objdump -t $1 >& $1.sym

./extractmdis $1
# extractasm $1
./getarg $1

./buildcfg $1

#  perl ~/util/findvar.pl $1
#  editsymb $1
fi
